spring:
  application:
    name: itoken-service-upload
  boot:
    admin:
      client:
        url: http://192.168.231.129:8084
  zipkin:
    base-url: http://192.168.231.129:9411

server:
  port: 8505

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.231.129:8761/eureka/,http://192.168.231.129:8861/eureka/,http://192.168.231.129:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

fastdfs.base.url: http://192.168.231.129:9999/
storage:
  type: fastdfs
  fastdfs:
    tracker_server: 192.168.231.129:22122