spring:
  application:
    # 服务名称
    name: itoken-eureka
  # 服务链路追踪Zipkin客户端
  zipkin:
    base-url: http://localhost:9411
  # 配置admin
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8761

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  instance:
    hostname: localhost
  client:
    # false是服务端 true是客户端
    # 生产环境要改成true，组Eureka集群，其实就是Eureka注册Eureka，互相注册
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 组集群要配置空间，不同的地址用逗号分隔
      # http://ip:${server.port}/eureka/,
      # http://ip:${server.port}/eureka/,
      # http://ip:${server.port}/eureka/