spring:
  application:
    name: itoken-zipkin
  # 配置admin
  boot:
    admin:
      client:
        url: http://192.168.231.129:8084
  zipkin:
    base-url: http://192.168.231.129:9411


server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.231.129:8761/eureka/,http://192.168.231.129:8861/eureka/,http://192.168.231.129:8961/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoint:
    health:
      show-details: always
    endpoints:
      web:
        exposure:
          include: health,info