spring:
  boot:
    admin:
      client:
        url: http://192.168.231.129:8084
  zipkin:
    base-url: http://192.168.231.129:9411

mybatis:
  type-aliases-package: com.gxx.itoken.common.domain
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.231.129:8761/eureka/,http://192.168.231.129:8861/eureka/,http://192.168.231.129:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info